---
driver:
  name: vagrant
  vm_hostname: <%= ENV['DS'] %>
  customize:
    memory: <%= ENV['DSR'] %>
    cpus: <%= ENV['DSC'] %>
    name: <%= ENV['DS'] %>
  network:
   - ['private_network', ip: <%= ENV['DSP'] %>]

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  # always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: mycsc-7.5
  # - name: centos-7
  # - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[db2::make_tcr]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
